testE: testEntity.cpp ../src/elements/Entity.cpp ../src/elements/AnimatedSprite.cpp ../src/elements/BoundingShape.cpp
	g++ -g -Wall -pedantic -o testE testEntity.cpp ../src/elements/Entity.cpp ../src/elements/AnimatedSprite.cpp ../src/elements/BoundingShape.cpp -lsfml-graphics -lsfml-window -lsfml-system
